compose/docker-compose.am-shib.yml
Set environment variables for Dashboard and Storage service to switch Shibboleth authentication on when configured.
AM pull request: https://github.com/JiscRDSS/archivematica/pull/20
SS pull request: https://github.com/JiscRDSS/archivematica-storage-service/pull/6
=> Set shibboleth auth flags

compose/docker-compose.dev.yml
If you're testing this branch, run:
$ docker-compose up -d --force-recreate minio rdss-archivematica-msgcreator
Only changes minio and msgcreator ports.
- minio: http://127.0.0.1:50500
- rdss-archivematica-msgcreator: http://127.0.0.1:50501
=> Compose: static ports minio and msgcreator

compose/am-shib/nginx/templates/am-shib.conf.tpl, compose/dev/etc/nginx/conf.d/archivematica.conf, compose/dev/etc/nginx/incs/msgcreator.inc, compose/docker-compose.dev.yml
We want to make sure that we'll be able to access to msgcreator in our QA environment via the standard 443/tcp port as we expect non-standard ports to be blocked by institutional firewalls.
I've tested this without shib and it works. Now building am-shib to see if it works.
=> Problem: msgcreator is not accessible via https (443/tcp)

compose/.env, compose/Makefile, compose/README.md, compose/docker-compose.dev.yml
This addresses issue #35.
I've changed the definition of the `archivematica_pipeline_data` and `archivematica_storage_service_data` volumes so that they are now external. This means that `docker-compose` will not attempt to create them for us, we have to create them ourselves using [docker volume](https://docs.docker.com/engine/reference/commandline/volume_create/). However the new `make create-local-volumes` and `make create-nfs-volumes` targets, which need to be run before `make all` do this for us.
As the names suggest, I've made it so that the external volumes can be either 'local' (via a bind mount) or 'remote', using NFS. This should facilitate use in both dev and production environments.
I've updated the readme with instructions on how to configure these volumes.
TL;DR here's the …
=> Compose: use named volumes for pipeline and storage service data

compose/shib-local/Makefile, compose/shib-local/etc/idp/service-providers.json, compose/shib-local/idp-metadata-providers.py, compose/shib-local/idp/README.md
Changed to use NGINX_HOSTNAME instead of DOMAIN_NAME because this is actually
more accurate in terms of our intent.
This fixes #33.
=> Compose: fix IdP metadata to correctly use env vars in configuration

compose/.env, compose/Makefile, compose/README.md, compose/docker-compose.dev.yml
When we tried to actually use the [docker volumes for NFS](https://docs.docker.com/engine/reference/commandline/volume_create/#driver-specific-options) we added in PR #36 they wouldn't connect. 
I've therefore replaced them with local bind mounts, in the expectation that 'local' folders
can actually be mounted NFS volumes, thereby delagating to the OS rather than doing it
in Docker. This is much simpler anyway.
This is another fix for #35.
=> Compose: removed use of nfs named volumes because they're broken

.gitignore, publish-images-playbook.yml
Use Ansible with `connection: local` and its `git` and `docker_image` modules to clone the git repositories, build the images and push them. You need at least Ansible 2.2 to be able to push images.
If Ansible happens to be the choice for other kind of deployment processes I'd like this solution to be considered. Ansible adds a level of idempotence that would be harder to achieve with regular scripting (e.g. `git-clone` can be problematic).
Usage:
```
$ git clone https://github.com/JiscRDSS/rdss-archivematica && cd rdss-archivematica
$ ansible-playbook \
rdss-publish-images-playbook.yml \
--extra-vars="registry=aws_account_id.dkr.ecr.region.amazonaws.com/"
```
The playbook fails if `registry` is undefined.
=> Add playbook to build and publish images

compose/shib-local/ldap/Dockerfile
Ideally we should update to use debian 9, but that is lower priority than
getting the image working again.
Fixes issue #60.
=> Compose: pin openldap image to use debian 8 instead of debian 9

compose/shib-local/idp/bootstrap.sh
The /opt/jre-home symlink is already present in the base image, so just reusing that.
This fixes #61.
=> Compose: update idp image to avoid hard coded Zulu version

publish-images-playbook.yml
We're working on a bigger update of the channel adapter incorporating features like the local data repository or better schema support - this will eventually reach `master` so I thought it's probably a good idea to pin this repo to the latest release available: `v0.1.2`.
=> Update channel adapter to v0.1.2

compose/dev/Makefile
The most recent version of the create_user command in SS needs an extra flag
`--superuser` to have the user created with the superuser mode. This is
required in our Compose environment because we use this user to set up the
pipeline.
=> Problem: Compose bootstrap fails to set up pipeline in SS

publish-images-playbook.yml, publish-qa-images-playbook.yml
The images we release to Jisc are built by the existing `publish-images-playbook.yml` Ansible playbook. However, this does not include the additional images we require in our own QA environment, such as MsgCreator and the DynamoDB, Kinesis and S3 mocks, Dynalite, Kinelite and Minio.
This pull request adds another playbook to build these in the same fashion as the main images. This will not be used by Jisc, but will be used by us internally for dev and QA purposes.
The images it builds are based on those that are required for the 'dev' Docker Compose configuration. It does not currently include those images required for our local Shibboleth services.
As we move to semver we can pin down the `version` for the repos and images defined in the playbook from branch names to tags, as has already …
=> Add playbook for supporting/QA docker images

compose/dev/.gitignore, compose/dev/etc/minio/config.json
minio keeps producing a new version of the configuration file and this pr just commits it so it doesn't show up in the git unstated area as a modified file which is annoying. It also ignores the .old version which we don't need since we're using git to track changes anyways. This PR also adds /src/rdss-archivematica-automation-tools to gitignore.
=> Compose: update minio config

publish-images-playbook.yml, publish-qa-images-playbook.yml
The new version of the channel adapter includes exponential back-off retry in the Archivematica client.
=> Bump channel adapter to v0.2.5

compose/dev/etc/mysql/my.cnf, compose/docker-compose.dev.yml
This config file has been set to support large transfer (more than 20GB). It is based on the default config file of the percona 5.5 docker official repository.
Changes added to the default config file:
a) innodb_log_file_size = 1G
This will increase the redo log size to 2G (using 2 files).
b) max_allowed_packet = 64 MB
This change allows large insert MySQL queries. For example, at the end
of the sanitize step.
This closes #84 and allows the configuration of the MySQL server before and after the deployment.
=> Added configurable my.cnf file

compose/dev/etc/mysql/my.cnf
It closes #96.
After running dos2unix on my.cnf file this strange character in the first line has gone:
```
diff --git a/compose/dev/etc/mysql/my.cnf b/compose/dev/etc/mysql/my.cnf
index e6c9ad0..74efc90 100644
--- a/compose/dev/etc/mysql/my.cnf
+++ b/compose/dev/etc/mysql/my.cnf
@@ -1,4 +1,4 @@
-<U+FEFF>#
+#
#
```
=> compose: fix my.cnf typo

compose/docker-compose.dev.yml
This is part of the fix for https://github.com/JiscRDSS/rdss-archivematica/issues/63 (see also https://github.com/artefactual/archivematica-storage-service/issues/236)
Here we set an environment variable for the address that Storage Service needs to use to contact Dashboard.
See also https://github.com/JiscRDSS/archivematica-storage-service/pull/22
=> Configure pipeline URL into SS config

.travis.yml, .yamllint, publish-images-playbook.yml, publish-qa-images-playbook.yml
This pull request addresses issue #107. It changes the Ansible playbooks to tag the built docker images with the specific version number of the project the image is for, as well as the "latest" tag that is used currently.
Applying multiple tags to an image doesn't seem to be possible using the `docker_image` module in Ansible. Instead, I've changed the playbook to use the `command` module, which executes a `docker build -t name:vX.Y.Z -t name:latest .` command for each image.
Adding the version tag, and moving to using semver, has highlighted that we are repeating the version number across the `repos` and `images` collection variables in the playbooks. This is prone to introducing error - if one of the version strings is not updated correctly then it will introduce inconsistencies. It's …
=> Add specific version tags to docker images

publish-images-playbook.yml
Updating the ansible script for deploying images to use the most recent archivematica, storage service and automation tools repos.
Updatin nextcloud to use a non-rc tag.
fixes #105
=> Update images for 0.2.0 release

publish-qa-images-playbook.yml
This is a minor change to avoid the case where the main images playbook has already been executed and so the Git clone of the `rdss-archivematica-channel-adapter` repo already exists. If this happens, the git-clone task in the QA playbook will detect that nothing has changed, and the docker images for `minikine` and `dynalite` will not be built or published, causing deployment to fail.
Doing a separate checkout for the QA playbook fixes this.
This is necessary for PR #28 to work.
=> deployment: checkout QA copy of channel adapter to different folder

compose/docker-compose.qa.yml
In a previous commit for PR https://github.com/JiscRDSS/rdss-archivematica/pull/116 I changed the path that the `msgcreator` source gets checked out to. I forgot that the path was used in the QA compose config, as the path for a volume. Consequently the QA compose config broke if the `msgcreator` checkout didn't still exist in the old location.
This change fixes that, updating the QA compose config to use the correct new path.
=> compose: fix incorrect path for msgcreator checkout in QA config

.gitignore, compose/Makefile
@sevein has reported a problem whereby the make build for compose doesn't work when using `ENV=dev`:
`docker-compose up -d
ERROR: .IOError: [Errno 2] No such file or directory: u'./""/home/jesus/ram/compose/docker-compose.dev.yml'
make: *** [up] Error 1`
Turns out it's not always a good idea to quote things: make was capturing the quotes as part of the string, which was being passed to docker-compose, rather than just being used to capture the full string.
=> compose: fix broken make when using dev environment

compose/Makefile, compose/docker-compose.nextcloud.yml, compose/docker-compose.qa.yml, compose/qa/Makefile
In the compose configuration we're currently using a Docker named volume for storing MySQL data, `mysql_data`. However, this is a Docker-managed named volume, so every time the containers are redeployed it gets destroyed and recreated - causing the data in the database to be lost.
This pull request addresses issue #118 by changing `mysql_data` to be an external Docker volume, which means that Docker won't attempt to manage it itself so won't destroy it when the container is torn down.
I've also changed the bootstrap tasks in the Makefile, which were using `DROP IF EXISTS` instead of `CREATE IF NOT EXISTS` when creating the application databases. As part of this I've also replaced the arbitrary `@sleep 30` command with a more correct `until... done` loop, which waits until an actual SQL …
=> Use external docker volumes for MySQL data

publish-images-playbook.yml, publish-qa-images-playbook.yml
This addresses issue #125.
When using a non-semver "version" like a branch name (e.g. `qa/jisc`) the string being used to tag built Docker images wasn't valid syntax according to the Docker tag format. This fixes that, replacing invalid characters with `_` (currently only `/`, since this is the most likely to appear within a branch name). We also truncate the name string to 128, to adhere to the limit imposed by Docker.
=> compose: fix playbooks to always use valid docker tags

compose/docker-compose.dev.yml, compose/docker-compose.qa.yml
This pull request addresses #127. 
The source volume mounts were only intended to allow "hot" changes during development, so should be in dev, not in QA.
I've tested these changes in deployment and the services appear to still work as intended, so assigning to @sevein for review.
=> compose: move source volume mounts from QA to dev

.travis.yml, aws/machine/.gitignore, aws/machine/Makefile, aws/machine/README.md, aws/machine/deploy.sh, aws/machine/etc/.gitignore, aws/machine/etc/deployment.conf.template, aws/machine/etc/userdata/nfs, aws/machine/lib/lib-aws.sh, aws/machine/lib/lib-config.sh, aws/machine/lib/lib-docker.sh, aws/machine/lib/lib-logging.sh, aws/machine/lib/lib-remote-mounts.sh, aws/machine/lib/lib-session.sh, aws/machine/lib/libs.sh, aws/machine/teardown.sh
**UPDATE: This has evolved over the past few months and so is more than the original pull request was aiming for. See my latest comment below for better description of the work/change that this introduces.**
I've added a `provision-and-deploy.sh` script that basically carries out all of the steps that were previously described in the README, but does them automatically. The only thing you have to do is authenticate with AWS (which the script helps with too).
The script attempts to:
1. Get an active AWS session to use, challenging the user and creating a new one if there isn't one, including MFA auth
1. Determine the status of the target EC2 instance for Docker Machine to use, creating (provisioning) one if it doesn't exist, or starting it if it is stopped.
1. Copy the required source …
=> Add AWS deployment scripts

aws/machine/README.md, compose/Makefile
The Docker Compose configuration currently creates (`mkdir`) the directories for the `automated` and `interactive` workflows but does not set their permissions correctly, meaning that NextCloud is unable to upload into them. This pull request fixes that.
I've also shoehorned in a few minor fixes to the AWS machine README.md into this PR, as I forgot to add them to PR #28 prior to merging and they're too minor to raise a new PR for. Hopefully you can forgive me this transgression! 🙂
=> Compose: Allow other users to write to SS storage 

compose/dev/Makefile, compose/qa/Makefile
This commit adds a new targe `bootstrap-dashboard-frontend` that makes possible
to build the front-end apps `transfer-browser` and `appraisal-tab` inside the
container. The Docker image already has the apps built, this is a convenience
for the developer to update its working directory when needed.
This depends on https://github.com/JiscRDSS/archivematica/pull/47.
Related:
- [RDSSARK-229](https://jiscdev.atlassian.net/browse/RDSSARK-229)
- https://github.com/JiscRDSS/rdss-archivematica/issues/41
=> Compose: add bootstrap-dashboard-frontend target

publish-images-playbook.yml, publish-qa-images-playbook.yml
This updates the `JiscRDSS/archivematica` version to `v0.2.0-rc1`and the Channel Adapter to `v0.3.0`. Also updates the MsgCreator to `v0.1.0`.
Once we pass QA for this release the `JiscRDSS/archivematica` version can be set to `v0.2.0` and this repo's version can be tagged as `v0.3.0`. This will be done in another PR.
=> deployment: update playbooks for v0.3.0-rc1

Makefile, compose/dev/Makefile, compose/docker-compose.qa.yml, compose/qa/Makefile, publish-images-playbook.yml, publish-qa-images-playbook.yml
* Get version from git tags and write to yml file for build
* Run set-agent-code command on dashboard to override migration
I tried to get this working with docker `--build-args` but couldn't get the docker build to dynamically write a file containing the arg values that would actually show up on the image (possibly related to the order in which things are done during build?). So the makefile writes that file at the start of the build, and docker will pick it up and add it in to the image.
Archivematica PR: https://github.com/JiscRDSS/archivematica/pull/48
=> Set archivematica version and agent code

publish-images-playbook.yml
Changed the version of JiscRDSS/archivematica to `v0.2.0`.
**However...**
This pull request depends on [v0.2.0](https://github.com/JiscRDSS/archivematica/releases/tag/untagged-78eb6ec922177cf2a8ee) being out of draft status, otherwise the tag won't exist.
It also needs to be applied **before** 259ceb7bf50d1fb9d772821d143be14c288753f8 because the [change in JiscRDSS/archivematica](https://github.com/JiscRDSS/archivematica/commit/38a28ef8c1612e3869065fee132069a3d418d80e) that it depends on isn't in the `v0.2.0` release. Ideally this commit shouldn't have been merge to `master` yet, but since it has we need to cherry-pick it to a different branch (e.g. `develop`) so that it isn't lost and then revert the change in the `master` branch until this `v0.3.0` release is done.
=> Update playbook for v0.3.0 release

publish-images-playbook.yml
This change updates the playbook to include v0.3.0 of the Storage service.
Draft release notes for v0.4.0 of rdss-archivematica are here: https://jiscdev.atlassian.net/wiki/spaces/RDSSAR/pages/193889646/v0.4.0+Release+Notes+DRAFT
=> Deployment: Update playbook for v0.4.0-rc1 Release

Makefile, compose/dev/Makefile, compose/docker-compose.qa.yml, compose/qa/Makefile, publish-images-playbook.yml, publish-qa-images-playbook.yml
This was originally proposed in PR #129 but had to be reverted by PR #139 because it was merged to `master` during a code freeze for `v0.3.0`.
That release is now done, so we're good to go on merging it back in now.
=> Set archivematica version and agent code (again)

compose/Makefile, compose/docker-compose.qa.yml
In the compose configuration we're currently using a Docker named volume for storing elasticsearch data, elasticsearch_data. However, this is a Docker-managed named volume, so every time the containers are redeployed it gets destroyed and recreated - causing the elasticsearch data to be lost.
In the case of the automation-tools database, the transfer.db was also lost when redeploying, although in this case there was no docker-manager named volume for this. 
When this happened, all transfers in the automated transfer directory were reprocessed.
So, two external volumes have been created:
- rdss_elasticsearch_data: Elasticsearch data directory.
- rdss_am-autotools-data: Automationtools directory that contains the transfers.db file.
This PR closes #133.
=> Use elasticsearch data and autotools db as external volumes.

compose/dev/Makefile, compose/docker-compose.qa.yml, compose/qa/Makefile, compose/qa/etc/rdss-create-storage-locations.py
When we deploy for RDSS we require two storage service locations to exist: `automated` and `interactive`. Currently, these need to be created manually after each (re)deployment.
This pull request addresses this by building on https://github.com/JiscRDSS/archivematica-storage-service/pull/24 by using the new API added in that PR to automate the creation of these storage locations during the bootstrap stage for the Storage Service container.
This is implemented as a simple Python script that uses the `requests` module (already installed in the Storage Service container) to interact with the SS via its API to check if the required locations exist and if not then create them. The Makefile `bootstrap-storage-service` target invokes this script within the `archivematica-storage-service` …
=> Add bootstrap for SS locations

Makefile, compose/.env, compose/Makefile, compose/dev/Makefile, compose/docker-compose.dev.yml, compose/docker-compose.qa.yml, compose/qa/Makefile, compose/qa/etc/rdss-create-storage-locations.py, compose/shib-local/idp/bootstrap.sh
This pull request addresses a number of different issues I've encountered when working with the current code in the `qa/0.5.0` branch. The changes are separated into different commits, to maintain atomicity.
Here's what's changed:
1. Fix race condition between IdP and SP. Since I removed the `sleep 30` from the bootstrap, it's unmasked a problem whereby there's a race between the IdP and SP, as both want to be able to retrieve the other's metadata XML. The IdP now parses its `metadata-providers.xml` and waits until all `metadataURL` endpoints are available before allowing the IdP web service to start.
1. Fix errors when creating the SS storage locations during bootstrap. When I added this to the bootstrap, I assumed that the correct place to do it was during the SS bootstrap. This was …
=> Compose fixes

compose/Makefile, compose/README.md, compose/docker-compose.nextcloud.yml, publish-images-playbook.yml
Recent changes in https://github.com/JiscRDSS/rdss-arkivum-nextcloud require we update the `nextcloud` service in our Docker Compose configuration. In particular, we need to:
1. Make all nextcloud volumes external, so that we persist state and app data correctly
1. Consolidate the 5 nextcloud volumes into `nextcloud_data` and `nextcloud_themes`
1. Add a dependency on the `redis` service, which is used for caching by nextcloud
The `nextcloud_data` volume is mounted as `/var/lib/nextcloud`, which is where NextCloud now stores all of its state and internal data files. In case you're wondering why `nextcloud_themes` is required, it's because the base image uses `/nextcloud/themes` as a volume, so it's not possible to change it without rewriting what is in the base image (which may be required …
=> Update nextcloud service to match latest image

compose/docker-compose.dev.yml
Since https://github.com/JiscRDSS/archivematica/pull/51/commits/e899d611616b0b2ba9a39d7e87087db45cc7aa4e the MCPClient now requires version information to be provided, so the compose build needs updating to do this.
Note that this change is dependent on an unreleased change on the https://github.com/JiscRDSS/archivematica/tree/qa/jisc branch, so we should wait for that to be released before merging this pull request.
=> Add version info to MCPClient build

aws/machine/deploy.sh
The ansible playbooks need the extra-variable rdss_version for v0.5.0 release.
This closes #156
=> Deployment: update deploy.sh for v0.5.0 release

aws/machine/deploy.sh
The latest commits have changed the following volumes to external:
* am-autotools-data
* elasticsearch-data
* nextcloud-data
* nextcloud-themes
The deploy.sh script was using the default path (/tmp).
This commit changes the path to:
* /mnt/am-autotools-data
* /mnt/elasticsearch-data
* /mnt/nfs/nextcloud-data
* /mnt/nfs/nextcloud-themes
Those are consistent with the rest of the paths. The nexcloud paths will use the nfs share because they will get large.
This fixes #160
=> update deploy.sh for new external volumes

compose/dev/Makefile, compose/qa/Makefile
I've recently been testing the setup and teardown with `make all ENV=dev` and found that, because the bootstrap destroys the database with a `DROP ... CREATE` for both `SS` and `MCP`, the resulting system that comes up on subsequent redeployments is inconsistent. Symptoms I've seen have included the default location in the SS having a blank `staging_path`, and the 5 required default locations that should be created by [this code](https://github.com/artefactual/archivematica-storage-service/blob/stable/0.11.x/storage_service/locations/models/pipeline.py#L125-L141).
The qa build does not exhibit these problems, because there we changed it to use `CREATE IF NOT EXISTS` instead of `DROP ... CREATE`. I'm therefore proposing that we do the same for dev, even if it means we have to clear down …
=> Use same bootstrap for dev as for qa

compose/Makefile, compose/README.md
We have the `create-volumes` target but no way to clean them up after destroy. This pull request adds a `destroy-volumes` target fills this gap, removing all of the docker volumes we create and also removing all files from the defined paths. This is obviously dangerous, so we ask the user to confirm their intent before doing anything.
Note that the removal of the files will likely require `sudo` rights, but I haven't put it in the script because I don't want to add a dependency on `sudo` rights actually into the Makefile itself.
This doesn't/shouldn't affect anything production based; it's mostly only of use in a development environment, since that's the only place where the various volume locations aren't going to be remote mounts.
=> compose: add destroy-volumes target

compose/.env, compose/docker-compose.qa.yml
Added the env variable `ES_HEAP_SIZE` for JVM HEAP size, ensuring that the min
(Xms) and max (Xmx) sizes are the same, preventing the heap from being resized
at runtime, a very costly process.
It closes #161
=> compose: Configure Elasticsearch heap size

publish-images-playbook.yml
I suggest that a new v0.6.0-rc2 tag be made for rdss-archivematica after this PR is approved and merged.
v0.5.0 of the channel adapter will not accept invalid messages
from samvera.  This may break in production at the moment.
v0.4.0 is safe to deploy to production, and there are no other
changes in v0.5.0 that are required at this time.
=> revert channel adapter to v0.4.0

publish-images-playbook.yml
This fixes the problem of environment variables not being retained when
executing NextCloud PHP code through php-fpm.
See https://github.com/JiscRDSS/rdss-arkivum-nextcloud/issues/9.
This is the only change planned for release v0.5.2.
=> update NextCloud version to v0.2.3

publish-images-playbook.yml
Updates the playbook to use `v0.2.4` of NextCloud. This depends on https://github.com/JiscRDSS/rdss-arkivum-nextcloud/pull/13 being approved and released as `v0.2.4` first.
=> update NextCloud image version to v0.2.4

publish-images-playbook.yml
This pull request includes two changes:
1. Update the NextCloud version to v0.2.5
1. Only tag images as `latest` if the version of the image or the `rdss_version` is not a release candidate (i.e. does not contain "rc" in the version string).
The latter of these was suggested because some production deployments are configured to use `latest` versions of the Docker images, rather than specific versions, so if this tag is updated with an `rc` version then a redeployment in production could inadvertently deploy an update.
@LondonAppDev are you able to confirm that this change meets your requirements for the `latest` tag?
=> update playbook for v0.5.4

compose/docker-compose.qa.yml
Otherwise the job "Characterize and extract metadata on submission
documentation" fails (group "Process submission documentation) with the
following error:
```
java.io.FileNotFoundException: /var/archivematica/sharedDirectory/tmp/fits.haEnq9/fits.xml (Read-only file system)
at java.io.FileOutputStream.open(Native Method)
at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
at java.io.FileOutputStream.<init>(FileOutputStream.java:110)
at edu.harvard.hul.ois.fits.Fits.outputResults(Fits.java:320)
at edu.harvard.hul.ois.fits.Fits.main(Fits.java:226)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at …
```
=> Compose: fits to mount sharedDir with rw perms

README.md, compose/README.md
A few things have changed lately with the build, particularly compose, that haven't made it into the readme docs, so newcomers to the project are left a little bewildered when trying to build for the first time.
This pull request updates the readme docs to include:
1. Mention of the two environments for the build, `dev` and `qa`.
1. Mention of the requirement to have a Docker registry for `qa` builds, and describe how to set this up locally.
=> Update readme docs

compose/Makefile, compose/dev/Makefile, compose/qa/Makefile
This deletes the builtin processing configs (automated and default)
so that MCP Server can recreate from the original configs when restarted.
Called before restart-mcp-services, if `RESET_PROCESSING_CONFIG` env var
is set to true. It is defined as a target in its own right in case there
is a need to call it manually.
See also https://github.com/JiscRDSS/archivematica/pull/67
=> Add reset-processing-configs target to Makefiles

compose/shib-local/idp/bin/init-idp.sh
This is as required by Jisc - they don't want to use SLO.
This builds on #188, so must be merged after that PR has been merged.
=> change Shibboleth IdP to only support local logout

aws/machine/lib/lib-docker.sh
This is because versions > 1.19.0 have a change in their behaviour (introduced in 1.19.0) that means that our use of docker-compose to exec a mysql command to test mysql connectivity during the bootstrap doesn't return the right status, so the deployment gets stuck waiting for the
mysql service to become ready.
There is also a different problem with v1.18.0, which attempts to use a newer version of the Docker API, which means that `docker-compose build` fails, hence why v1.17.0 is used here.
Fixes issue #191.
=> deployment: use docker-compose v1.17.0 by default

compose/.env, compose/docker-compose.am-shib.yml
This is so we can configure where we get the image from and with what version.
Based on @mamedin's work in the `dev/nextcloud-shibboleth-mamedin` branch.
=> compose: use registry and env var for shib-sp-proxy image version

compose/docker-compose.qa.yml
The consumer in the channel adapter uses a `builtin` storage implementation by
default that it doesn't write to disk. This commit tweaks the configuration of Compose so the deployment uses `dynamodb` implementation instead, supported by our local dynalite service.
=> Compose: set up dynamodb consumer storage

publish-images-playbook.yml, publish-qa-images-playbook.yml
This pull request updates each component image in the Ansible playbook to the version intended for inclusion in the v0.6.0 release.
Component versions:
* [Archivematica v0.6.0](https://github.com/JiscRDSS/archivematica/releases/tag/v0.6.0)
* [Automation Tools v0.2.0](https://github.com/JiscRDSS/rdss-archivematica-automation-tools/releases/tag/v0.2.0)
* [Channel Adapter v0.6.0](https://github.com/JiscRDSS/rdss-archivematica-channel-adapter/releases/tag/v0.6.0)
* [NextCloud v0.3.0](https://github.com/JiscRDSS/rdss-arkivum-nextcloud/releases/tag/v0.3.0)
* [Shibboleth SP Proxy v0.1.0](https://github.com/JiscRDSS/rdss-archivematica-shib-sp-proxy/releases/tag/v0.1.0)
* [Storage Service v0.4.0](https://github.com/JiscRDSS/archivematica-storage-service/releases/tag/v0.4.0)
All the above component …
=> Update playbook for v0.6.0 release

compose/docker-compose.am-shib.yml, compose/docker-compose.qa.yml
There are a couple of things to do with the NextCloud config in our Compose files that needs fixing.
1. We need to set `NEXTCLOUD_HOST` in our `qa` config, not just `am-shib`, because otherwise the default `nextcloud.example.ac.uk` is used as the host name in non-Shibboleth deployments.
1. We need to set the [newly added](https://github.com/JiscRDSS/rdss-arkivum-nextcloud/pull/23) `NEXTCLOUD_PORT` environment variable so that the port number is correct when building NextCloud URLs.
=> Compose: fix nextcloud config

publish-images-playbook.yml
This pull request updates the following image versions:
* Archivematica to [v0.6.5](https://github.com/JiscRDSS/archivematica/releases/tag/v0.6.5)
* NextCloud to [v0.5.0](https://github.com/JiscRDSS/rdss-arkivum-nextcloud/releases/tag/v0.5.0)
Other image versions remain unchanged.
This change is targeted towards v0.6.0-rc8 release.
=> Update image versions for v0.6.0-rc8

compose/docker-compose.qa.yml
We don't want to set the `NEXTCLOUD_HOST` or `NEXTCLOUD_PORT` env vars in the  `qa` config because NextCloud is able to detect the correct values itself.
The only time we need to use these is in the `am-shib` config, as there NextCloud is behind the SSL proxy, so we need to override the auto-detected values.
See also JiscRDSS/rdss-arkivum-nextcloud#27 which removes the defaults that are currently used if the environment variables aren't set.
=> compose: don't set NextCloud env vars in qa config

publish-images-playbook.yml
We need to update the NextCloud image to version 0.5.1 to take advantage of new default behaviour now that we're not setting the env vars in our `qa` config (see #210).
=> Update NextCloud to v0.5.1

.travis.yml, README.md, compose/.env, compose/Makefile, compose/docker-compose.qa.yml, compose/docker-compose.utils.yml, quickstart
With new people coming onto the project, it's become necessary for us to run different deployments simultaneously on the same Docker host.
In trying this, there were a couple of things preventing this from working, in particular the lack of automatic namespacing of deployments (all used a project name of `rdss`), difficult-to-override storage locations, and use of specific ports for exposing services, which by default was always the same (port 8888 for NextCloud, for example). The first commit therefore fixes this, allowing multiple deployments to the same Docker host to be possible.
However, though possible, it is still too difficult to achieve a new deployment, especially for novice users who aren't familiar with Docker or our applications. Even just setting up a registry in a …
=> Improvement: make Compose work in multi-user environment

aws/machine/README.md, aws/machine/etc/deployment.conf.template
Recent changes in our Docker images mean that 16G is no longer enough, so it's now increased to 40G. When I did a test deployment with a bigger volume, the usage on `/` was 17G, so 40G gives us a fair bit of overhead for the future.
=> deployment: increase default root size for dockerhost instance

compose/.env, compose/README.md, compose/docker-compose.dev.yml, compose/docker-compose.qa.yml
When working with queues in Jisc's Kinesis we will need to set the queue names. This pull request adds new `RDSS_ADAPTER_QUEUE_*` environment variables to make it easier to consistently set the queue names that the consumer and publisher should be using when working with the Kinesis streams.
Note that this assumes there are four streams, not three ("input" and "output", not "main"), so won't work with minikine unless https://github.com/JiscRDSS/rdss-archivematica-channel-adapter/commit/08f6f3a87513609f8a726e85bbbd36dcc378dc7c is included in the built minikine image (which at the moment means building from `master` of rdss-archivematica-channel-adapter rather than a tagged release).
=> compose: add environment variables for channel adapter queues

compose/.env, compose/docker-compose.mock-aws.qa.yml
The default queue names incorrectly had double quotes around them, which were being interpreted as part of the intended queue name, only double quotes aren't legal in stream names.
Also updated minikine config now that the image expects `input` and `output` queues rather than just `main`.
=> compose: fix channel adapter queue config

compose/Makefile, compose/README.md, compose/am-shib/Makefile, compose/dev/Makefile, compose/docker-compose.am-shib.dev.yml
This pull request fixes issues #218, #219 and #221:
* Adding a new `docker-compose.am-shib.dev.yml` file to use when deploying with Shibboleth and ENV=qa. (issue #218)
* Adding a new Makefile target to restart all containers at the end of the deploy (needed by Shibboleth) (issue #219)
* Adding the `build-nextcloud-apps` target to `dev/Makefile` (it is used by `qa/Makefile`) (issue #221)
=> compose: Shibboleth and ENV=dev fixes

compose/README.md, compose/docker-compose.dev.yml, compose/docker-compose.qa.yml
This commits removes the producer from the list of services being deployed.
This component is unused at the moment. We can introduce again when needed.
[RDSSARK-562](https://jiscdev.atlassian.net/browse/RDSSARK-562).
=> Disable adapter producer

compose/docker-compose.dev.yml
It's better to use `go install` because the final binary is written in
`$GOPATH/bin`. Otherwise the binary goes in the sources directory where
it's possible that we don't have write permissions.
=> Compose: msgcreator entrypoint use go install

compose/qa/Makefile
This was already done in `dev`, see `45789a7e94`.
=> Compose: add --site-url in QA env

compose/.env, compose/dev/Makefile, compose/docker-compose.qa.yml, compose/qa/Makefile, compose/qa/etc/rdss-create-s3-space-location.py, compose/qa/etc/rdss-create-storage-locations.py
This commit allows to create from compose an S3 Space and its AIP Store. The
following variables can be defined in the .env file:
- S3_AIP_STORE=false
- S3_AIP_STORE_ACCESS_KEY_ID="CHANGEME"
- S3_AIP_STORE_ENDPOINT_URL="https://s3.amazonaws.com"
- S3_AIP_STORE_PATH="/var/archivematica/storage_service"
- S3_AIP_STORE_REGION="ca-central-1"
- S3_AIP_STORE_SECRET_ACCESS_KEY="CHANGEME"
When setting `S3_AIP_STORE` as `true` the S3 Space and its AIP Store will be
created if needed with these variables on bootstrap.
It fixes #220
=> Compose: create s3 space and aip store

aws/machine/etc/deployment.conf.template
Minor fix to allow the Kinesis queue config in deployment.conf.template to be overridden by environment variables.
=> Channel adaptor Kinesis queue settings can be overridden by ENVVARs
